DROP TABLE IF EXISTS feed;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS film_like;
DROP TABLE IF EXISTS user_friends_status;
DROP TABLE IF EXISTS film_genre;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS film;
DROP TABLE IF EXISTS mpa;

CREATE TABLE IF NOT EXISTS mpa (
    mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name varchar(10)
);

CREATE TABLE IF NOT EXISTS film (
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name varchar(50),
    film_description varchar(255),
    release_date date,
    duration int,
    mpa_id INTEGER REFERENCES mpa(mpa_id)
);

CREATE TABLE IF NOT EXISTS users (
    users_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    email varchar(20) NOT NULL,
    login varchar(50) NOT NULL,
    birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS film_like (
    film_like_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id BIGINT NOT NULL REFERENCES film(film_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(users_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS genre (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name varchar(30)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_genre_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id BIGINT NOT NULL REFERENCES film(film_id) ON DELETE CASCADE,
    genre_id INTEGER NOT NULL REFERENCES genre(genre_id)
);

CREATE TABLE IF NOT EXISTS user_friends_status (
    user_friends_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(users_id) ON DELETE CASCADE,
    friend_id BIGINT NOT NULL REFERENCES users(users_id) ON DELETE CASCADE,
    status_of_friendship varchar(11),
    CONSTRAINT status_of_friendship_constraint CHECK (status_of_friendship = 'Confirmed'
    OR status_of_friendship = 'Unconfirmed')
);

CREATE TABLE IF NOT EXISTS reviews (
   reviews_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   content varchar(255) NOT NULL,
   is_positive BOOLEAN NOT NULL,
   user_id BIGINT NOT NULL REFERENCES users(users_id) ON DELETE CASCADE,
   film_id BIGINT NOT NULL REFERENCES film(film_id) ON DELETE CASCADE,
   useful BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS feed (
        event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        entity_id INTEGER,
        operation_name CHARACTER VARYING(10),
        event_type CHARACTER VARYING(10),
        timestamp LONG,
        user_id INTEGER NOT NULL REFERENCES users (users_id)
);